# Generated by Django 3.1.14 on 2023-05-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('template', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_additions.themeextension')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_additions.theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeoKeyWordExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.domainname')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('keywords', models.ManyToManyField(to='seo.SeoKeyWord')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='page_additions.seokeywordextension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
