# Generated by Django 3.1.14 on 2023-05-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('seo', '0001_initial'),
        ('page_additions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeoKeyWordExtension',
            new_name='SeoExtension',
        ),
    ]
