# Generated by Django 3.1.14 on 2023-05-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_domainname'),
        ('page_additions', '0003_domainname'),
    ]

    operations = [
        migrations.AddField(
            model_name='seokeywordextension',
            name='domain_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seo.domainname'),
            preserve_default=False,
        ),
    ]
