# Generated by Django 3.1.14 on 2023-05-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seoaddition_tags'),
        ('file_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='file',
            name='seo_addition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seo.seoaddition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='seo_addition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seo.seoaddition'),
            preserve_default=False,
        ),
    ]
