# Generated by Django 3.1.14 on 2023-05-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaddition',
            name='tags',
            field=models.ManyToManyField(to='seo.SeoTag'),
        ),
    ]
