# Generated by Django 3.1.14 on 2023-05-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auto_20230520_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoaddition',
            old_name='tags',
            new_name='keywords',
        ),
    ]
